In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list the files in the input directory

import os
print(os.listdir("../input"))

# Any results you write to the current directory are saved as output.

['test.csv', 'train.csv', 'svm_benchmark.csv']


In [2]:
train = pd.read_csv("../input/train.csv")
test = pd.read_csv("../input/test.csv")

In [3]:
train.head()

Activity        D1        D2    D3   D4        D5        D6        D7  \
0         1  0.000000  0.497009  0.10  0.0  0.132956  0.678031  0.273166   
1         1  0.366667  0.606291  0.05  0.0  0.111209  0.803455  0.106105   
2         1  0.033300  0.480124  0.00  0.0  0.209791  0.610350  0.356453   
3         1  0.000000  0.538825  0.00  0.5  0.196344  0.724230  0.235606   
4         0  0.100000  0.517794  0.00  0.0  0.494734  0.781422  0.154361   

         D8        D9  ...    D1767  D1768  D1769  D1770  D1771  D1772  D1773  \
0  0.585445  0.743663  ...        0      0      0      0      0      0      0   
1  0.411754  0.836582  ...        1      1      1      1      0      1      0   
2  0.517720  0.679051  ...        0      0      0      0      0      0      0   
3  0.288764  0.805110  ...        0      0      0      0      0      0      0   
4  0.303809  0.812646  ...        0      0      0      0      0      0      0   

   D1774  D1775  D1776  
0      0      0      0  
1      0      1      0  
2      0      0      0  
3      0      0      0  
4      0      0      0  

[5 rows x 1777 columns]

In [4]:
test.head()

D1        D2    D3   D4        D5        D6        D7        D8  \
0  0.366667  0.611765  0.05  0.0  0.110435  0.803973  0.106075  0.473965   
1  0.100000  0.758175  0.30  0.0  0.180128  0.621378  0.287144  0.503919   
2  0.100000  0.658812  0.10  0.0  0.243421  0.640959  0.312765  0.279784   
3  0.100000  0.655752  0.10  0.0  0.226978  0.776996  0.150657  0.336948   
4  0.000000  0.484851  0.00  0.0  0.561200  0.771463  0.244287  0.293096   

         D9       D10  ...    D1767  D1768  D1769  D1770  D1771  D1772  D1773  \
0  0.835617  0.106452  ...        1      1      1      1      0      1      0   
1  0.674919  0.403616  ...        0      0      0      0      0      0      0   
2  0.686775  0.280301  ...        0      0      0      0      0      0      0   
3  0.802121  0.125608  ...        0      0      0      0      0      0      0   
4  0.717575  0.230842  ...        0      0      0      0      0      0      0   

   D1774  D1775  D1776  
0      0      1      0  
1      0      0      0  
2      0      0      0  
3      0      0      0  
4      0      0      0  

[5 rows x 1776 columns]

In [5]:
pd.options.display.max_columns = 999
pd.options.display.max_rows = 999

In [6]:
train.isnull().sum()

Activity    0
D1          0
D2          0
D3          0
D4          0
D5          0
D6          0
D7          0
D8          0
D9          0
D10         0
D11         0
D12         0
D13         0
D14         0
D15         0
D16         0
D17         0
D18         0
D19         0
D20         0
D21         0
D22         0
D23         0
D24         0
D25         0
D26         0
D27         0
D28         0
D29         0
D30         0
D31         0
D32         0
D33         0
D34         0
D35         0
D36         0
D37         0
D38         0
D39         0
D40         0
D41         0
D42         0
D43         0
D44         0
D45         0
D46         0
D47         0
D48         0
D49         0
D50         0
D51         0
D52         0
D53         0
D54         0
D55         0
D56         0
D57         0
D58         0
D59         0
D60         0
D61         0
D62         0
D63         0
D64         0
D65         0
D66         0
D67         0
D68         0
D69         0
D70         0
D71   

In [7]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3751 entries, 0 to 3750
Columns: 1777 entries, Activity to D1776
dtypes: float64(942), int64(835)
memory usage: 50.9 MB


In [8]:
train.nunique()

Activity       2
D1            24
D2          1768
D3            15
D4             5
D5          2923
D6          3732
D7          3685
D8          3272
D9          3741
D10         3692
D11          265
D12           12
D13           20
D14         2390
D15         3682
D16         3166
D17         3749
D18         3212
D19         2134
D20         1531
D21         1033
D22           17
D23            2
D24            5
D25         2943
D26         3280
D27            2
D28            2
D29            7
D30         3671
D31         1325
D32         1141
D33          387
D34          161
D35          121
D36           72
D37           73
D38          647
D39          458
D40           74
D41           55
D42           70
D43          156
D44          200
D45         2610
D46         3334
D47         3131
D48          732
D49          345
D50           26
D51            2
D52          208
D53          202
D54          461
D55          356
D56          254
D57          108
D58          2

In [9]:
y = train["Activity"]
X = train.drop(['Activity'],axis=1)

In [10]:
from catboost import CatBoostClassifier 

In [11]:
#model = CatBoostClassifier(random_state = 42, depth = 5)

In [12]:
#model.fit(X, y, )

In [13]:
#model = CatBoostClassifier(random_state = 42, depth = 8)

In [14]:
#model.fit(X, y, )

In [15]:
model = CatBoostClassifier(random_state = 42, depth = 8)
#8이 일단 제일 좋았다

In [16]:
model.fit(X, y, )

Learning rate set to 0.024356
0:	learn: 0.6841492	total: 1.31s	remaining: 21m 53s
1:	learn: 0.6761613	total: 1.78s	remaining: 14m 46s
2:	learn: 0.6694673	total: 2.62s	remaining: 14m 29s
3:	learn: 0.6616356	total: 3.47s	remaining: 14m 24s
4:	learn: 0.6562659	total: 4.3s	remaining: 14m 16s
5:	learn: 0.6506889	total: 5.16s	remaining: 14m 14s
6:	learn: 0.6449609	total: 6.02s	remaining: 14m 14s
7:	learn: 0.6389500	total: 6.88s	remaining: 14m 13s
8:	learn: 0.6325856	total: 7.75s	remaining: 14m 13s
9:	learn: 0.6279650	total: 8.59s	remaining: 14m 10s
10:	learn: 0.6224187	total: 9.44s	remaining: 14m 8s
11:	learn: 0.6170744	total: 10.3s	remaining: 14m 5s
12:	learn: 0.6125551	total: 11.1s	remaining: 14m 3s
13:	learn: 0.6087373	total: 12s	remaining: 14m 2s
14:	learn: 0.6040541	total: 12.8s	remaining: 14m 1s
15:	learn: 0.6002428	total: 13.7s	remaining: 14m 1s
16:	learn: 0.5967408	total: 14.5s	remaining: 14m
17:	learn: 0.5925395	total: 15.4s	remaining: 13m 59s
18:	learn: 0.5886837	total: 16.2s	remai

In [17]:
sumit = pd.read_csv("../input/svm_benchmark.csv")

In [18]:
sumit.head()

MoleculeId  PredictedProbability
0           1              0.858294
1           2              0.867819
2           3              0.184781
3           4              0.831901
4           5              0.190208

In [19]:
preds = model.predict_proba(test)

In [20]:
preds[:,1:2]

array([[0.91168377],
       [0.96566351],
       [0.3523444 ],
       ...,
       [0.94376753],
       [0.77357951],
       [0.11493836]])

In [21]:
preds.shape

(2501, 2)

In [22]:
sumit.shape

(2501, 2)

In [23]:
pred = preds[:,1:2]

In [24]:
pred

array([[0.91168377],
       [0.96566351],
       [0.3523444 ],
       ...,
       [0.94376753],
       [0.77357951],
       [0.11493836]])

In [25]:
pred.shape

(2501, 1)

In [26]:
pred = pred.reshape(2501,)

In [27]:
pred.shape

(2501,)

In [28]:
pred

array([0.91168377, 0.96566351, 0.3523444 , ..., 0.94376753, 0.77357951,
       0.11493836])

In [29]:
preds = model.predict(test)
submit  = pd.DataFrame({'MoleculeId': sumit['MoleculeId'], 'PredictedProbability': pred})


In [30]:
submit.head()

MoleculeId  PredictedProbability
0           1              0.911684
1           2              0.965664
2           3              0.352344
3           4              0.900947
4           5              0.025638

In [31]:
submit.to_csv('result.csv', index=False)